networks:
  swims_network:

services:
  swims_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: swims
      POSTGRES_DB: swimsdb
    networks:
      - swims_network

  swims_wildfly:
    networks:
      - swims_network
    depends_on:
      - swims_postgres
