volumes:
  swims_postgres_data_dev:
  swims_limesurvey_surveys_dev:

services:
  swims_postgres:
    container_name: swims-postgres-dev
    volumes:
      - swims_postgres_data_dev:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  swims_limesurvey:
    image: docker.io/martialblog/limesurvey:5-apache
    container_name: swims-limesurvey-dev
    volumes:
      - swims_limesurvey_surveys_dev:/var/www/html/upload/surveys
      - ./docker/dev/limesurvey/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
    environment:
      DB_HOST: swims-postgres-dev
      DB_PASSWORD: admin
      ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"

  swims_wildfly:
    image: docker.io/bitnami/wildfly:26
    container_name: swims-wildfly-dev
    volumes:
      - ./docker/dev/wildfly/standalone.xml:/bitnami/wildfly/configuration/standalone.xml:ro
    environment:
      WILDFLY_PASSWORD: adminadmin
      WILDFLY_USERNAME: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: swims-postgres-dev
      LIMESURVEY_FIRST_ADMIN_PASSWORD: admin
      LIMESURVEY_HOST: swims-limesurvey-dev
      LIMESURVEY_PUBLIC_HOST: localhost
      LIMESURVEY_PUBLIC_PORT: 8081
      LIMESURVEY_USES_SSL: false
      LIMESURVEY_REMOTECONTROL_USES_SSL: false
      TABLEAU_USER: ${TABLEAU_USER}
      TABLEAU_SECRET: ${TABLEAU_SECRET}
      TABLEAU_SECRET_ID: ${TABLEAU_SECRET_ID}
      TABLEAU_CLIENT_ID: ${TABLEAU_CLIENT_ID}
    ports:
      - "8080:8080"
