volumes:
  swims_postgres_data_dev:

services:
  swims_postgres:
    container_name: swims-postgres-dev
    volumes:
      - swims_postgres_data_dev:/var/lib/postgres
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  swims_wildfly:
    image: docker.io/bitnami/wildfly:26
    container_name: swims-wildfly-dev
    volumes:
      - ./docker/dev/wildfly/standalone.xml:/bitnami/wildfly/configuration/standalone.xml:ro
    environment:
      - WILDFLY_PASSWORD=adminadmin
      - WILDFLY_USERNAME=admin
    ports:
      - "8080:8080"
