networks:
  swims_network:

volumes:
  swims_caddy_data:
  swims_caddy_config:

services:
  swims_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: swims
      POSTGRES_DB: swimsdb
    networks:
      - swims_network

  swims_limesurvey_mysql:
    image: docker.io/mysql:5.7
    environment:
      MYSQL_USER: limesurvey_swims
      MYSQL_DATABASE: limesurvey_swimsdb
    networks:
      - swims_network

  swims_limesurvey:
    environment:
      DB_NAME: limesurvey_swimsdb
      DB_USERNAME: limesurvey_swims
      BASE_URL: /limesurvey
    networks:
      - swims_network
    depends_on:
      - swims_limesurvey_mysql

  swims_wildfly:
    networks:
      - swims_network
    depends_on:
      - swims_postgres
      - swims_limesurvey

  caddy:
    networks:
      - swims_network
    depends_on:
      - swims_wildfly
