networks:
  swims_network:

services:
  swims_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: swims
      POSTGRES_DB: swimsdb
    networks:
      - swims_network

  swims_limesurvey:
    environment:
      DB_TYPE: pgsql
      DB_TABLE_PREFIX: limesurvey_
      DB_NAME: swimsdb
      DB_USERNAME: swims
      DB_PORT: 5432
      BASE_URL: ${LIMESURVEY_BASE_URL:-/limesurvey}
      ADMIN_USER: swims
      LISTEN_PORT: 8080
    networks:
      - swims_network
    depends_on:
      - swims_postgres

  swims_wildfly:
    environment:
      LIMESURVEY_BASE_URL: ${LIMESURVEY_BASE_URL:-/limesurvey}
      LIMESURVEY_ADMIN_USER: swims
      LIMESURVE_ON_SAME_NETWORK: true
      LIMESURVEY_PORT: 8080
    networks:
      - swims_network
    depends_on:
      - swims_postgres
      - swims_limesurvey